import React, { createContext, useContext, useState, useEffect } from 'react';

type Theme = 'light' | 'dark';
type Language = 'en' | 'es' | 'fr' | 'de' | 'hi' | 'ur';

interface SettingsContextType {
  theme: Theme;
  language: Language;
  direction: 'ltr' | 'rtl';
  setTheme: (theme: Theme) => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    settings: 'Settings',
    profile: 'Profile',
    theme: 'Theme',
    language: 'Language',
    light: 'Light',
    dark: 'Dark',
    save: 'Save Changes',
    logout: 'Logout',
    dashboard: 'Dashboard',
    edit_profile: 'Edit Profile',
    full_name: 'Full Name',
    email: 'Email Address',
    bio: 'Bio',
    avatar_url: 'Avatar URL',
    appearance: 'Appearance',
    preferences: 'Preferences',
    vault: 'The Vault',
    citizen: 'Citizen',
    verification_status: 'Verification Status',
    live_ballots: 'Live Ballots',
    history: 'Relational History',
    stats: 'Network Statistics',
    directives: 'Directives',
    start_verification: 'Start Verification',
    role: 'Role',
    voter: 'Voter',
    candidate: 'Candidate',
    switch_role: 'Switch Role',
    hero_title: 'Democracy, Refined.',
    hero_subtitle: 'The world\'s most advanced voting platform. Secure identity verification, real-time AI analysis, and absolute cryptographic transparency.',
    begin_journey: 'Begin Your Journey',
    view_protocol: 'View Protocol',
    zero_knowledge: 'Zero Knowledge',
    zero_knowledge_desc: 'Your identity is verified but your vote remains mathematically private and immutable.',
    ai_clarity: 'AI Clarity',
    ai_clarity_desc: 'Instant cross-referencing of candidate platforms versus historical voting data via VoteEase AI.',
    total_audit: 'Total Audit',
    total_audit_desc: 'Verify your individualized audit trail to ensure your voice was counted exactly as intended.',
    journey_title: 'The VoteEase Journey',
    journey_subtitle: 'Four steps to a more transparent future.',
    biometric_onboarding: 'Biometric Onboarding',
    biometric_desc: 'Securely link your identity using decentralised identifiers (DIDs) and biometric verification.',
    platform_discovery: 'Platform Discovery',
    platform_discovery_desc: 'Interact with candidate AI clones to understand their nuances without traditional media bias.',
    secure_balloting: 'Secure Balloting',
    secure_balloting_desc: 'Cast your vote within an E2EE environment accessible from any verified device globally.',
    vault_verification: 'Vault Verification',
    vault_verification_desc: 'Receive your cryptographic receipt in your Voter Vault, locked with your unique key.',
    ready_to_lead: 'Ready to lead the way?',
    join_millions: 'Join 14 million verified global citizens participating in the next evolution of governance.',
    create_identity: 'Create Your Voter Identity',
    vision_matrix: 'Interactive Vision Matrix',
    vision_matrix_desc: 'MAP CORE BELIEFS TO REAL-WORLD DATA OUTCOMES',
    login_voter: 'Voter Gateway',
    login_candidate: 'Candidate Portal',
    auth_vector: 'Choose your secure authentication vector.',
    voter_id: 'Voter ID',
    mobile_phone: 'Mobile Phone',
    global_account: 'Global Account',
    candidate_hash: 'Candidate Hash ID',
    official_credentials: 'Official Credentials',
    corporate_email: 'Use Corporate Email',
    identity_number: 'Identity Number',
    request_validation: 'Request Validation',
    switch_method: 'Switch Method',
    security_notice: 'Security Notice: This portal utilizes End-to-End Encryption. No raw credentials are stored on central nodes.',
    login_failed: 'Login failed. Please check your credentials and try again.',
    help_support: 'Help & Support'
  },
  es: {
    settings: 'Configuraciones',
    profile: 'Perfil',
    theme: 'Tema',
    language: 'Idioma',
    light: 'Claro',
    dark: 'Oscuro',
    save: 'Guardar cambios',
    logout: 'Cerrar sesión',
    dashboard: 'Tablero',
    edit_profile: 'Editar perfil',
    full_name: 'Nombre completo',
    email: 'Correo electrónico',
    bio: 'Biografía',
    avatar_url: 'URL del avatar',
    appearance: 'Apariencia',
    preferences: 'Preferencias',
    vault: 'La Bóveda',
    citizen: 'Ciudadano',
    verification_status: 'Estado de Verificación',
    live_ballots: 'Boletas en Vivo',
    history: 'Historial Relacional',
    stats: 'Estadísticas de Red',
    directives: 'Directivas',
    start_verification: 'Iniciar Verificación',
    role: 'Rol',
    voter: 'Votante',
    candidate: 'Candidato',
    switch_role: 'Cambiar Rol',
    hero_title: 'Democracia, Refinada.',
    hero_subtitle: 'La plataforma de votación más avanzada del mundo. Verificación de identidad segura, análisis de IA en tiempo real y transparencia criptográfica absoluta.',
    begin_journey: 'Comience su viaje',
    view_protocol: 'Ver Protocolo',
    zero_knowledge: 'Conocimiento Cero',
    zero_knowledge_desc: 'Su identidad es verificada pero su voto permanece matemáticamente privado e inmutable.',
    ai_clarity: 'Claridad de IA',
    ai_clarity_desc: 'Referencia cruzada instantánea de plataformas de candidatos frente a datos históricos de votación a través de VoteEase AI.',
    total_audit: 'Auditoría Total',
    total_audit_desc: 'Verifique su rastro de auditoría individualizado para asegurarse de que su voz fue contada exactamente como se pretendía.',
    journey_title: 'El viaje de VoteEase',
    journey_subtitle: 'Cuatro pasos hacia un futuro más transparente.',
    biometric_onboarding: 'Incorporación Biométrica',
    biometric_desc: 'Vincule su identidad de forma segura utilizando identificadores descentralizados (DID) y verificación biométrica.',
    platform_discovery: 'Descubrimiento de Plataforma',
    platform_discovery_desc: 'Interactúe con clones de IA de candidatos para comprender sus matices sin el sesgo de los medios tradicionales.',
    secure_balloting: 'Votación Segura',
    secure_balloting_desc: 'Emita su voto dentro de un entorno E2EE accesible desde cualquier dispositivo verificado globalmente.',
    vault_verification: 'Verificación de la Bóveda',
    vault_verification_desc: 'Reciba su recibo criptográfico en su Bóveda de Votante, bloqueado con su clave única.',
    ready_to_lead: '¿Listo para liderar el camino?',
    join_millions: 'Únase a 14 millones de ciudadanos globales verificados que participan en la próxima evolución de la gobernanza.',
    create_identity: 'Cree su identidad de votante',
    vision_matrix: 'Matriz de Visión Interactiva',
    vision_matrix_desc: 'MAPEO DE CREENCIAS CENTRALES A RESULTADOS DE DATOS DEL MUNDO REAL',
    login_failed: 'Error de inicio de sesión. Por favor, compruebe sus credenciales e inténtelo de nuevo.',
    help_support: 'Ayuda y Soporte'
  },
  fr: {
    settings: 'Paramètres',
    profile: 'Profil',
    theme: 'Thème',
    language: 'Langue',
    light: 'Clair',
    dark: 'Sombre',
    save: 'Enregistrer',
    logout: 'Déconnexion',
    dashboard: 'Tableau de bord',
    edit_profile: 'Modifier le profil',
    full_name: 'Nom complet',
    email: 'Adresse e-mail',
    bio: 'Bio',
    avatar_url: 'URL de l\'avatar',
    appearance: 'Apparence',
    preferences: 'Préférences',
    vault: 'Le Coffre',
    citizen: 'Citoyen',
    verification_status: 'Statut de Vérification',
    live_ballots: 'Scrutins en Direct',
    history: 'Historique Relationnel',
    stats: 'Statistiques Réseau',
    directives: 'Directives',
    start_verification: 'Démarrer la Vérification',
    role: 'Rôle',
    voter: 'Électeur',
    candidate: 'Candidat',
    switch_role: 'Changer de Rôle',
    hero_title: 'Démocratie, Raffinée.',
    hero_subtitle: 'La plateforme de vote la plus avancée au monde. Vérification d\'identité sécurisée, analyse IA en temps réel et transparence cryptographique absolue.',
    begin_journey: 'Commencer votre voyage',
    view_protocol: 'Voir le protocole',
    zero_knowledge: 'Connaissance Zéro',
    zero_knowledge_desc: 'Votre identité est vérifiée mais votre vote reste mathématiquement privé et immuable.',
    ai_clarity: 'Clarté de l\'IA',
    ai_clarity_desc: 'Referencement croisé instantané des programmes des candidats par rapport aux données de vote historiques via VoteEase AI.',
    total_audit: 'Audit Total',
    total_audit_desc: 'Vérifiez votre piste d\'audit individualisée pour vous assurer que votre voix a été comptée exactement comme prévu.',
    journey_title: 'Le voyage VoteEase',
    journey_subtitle: 'Quatre étapes vers un avenir plus transparent.',
    biometric_onboarding: 'Intégration Biométrique',
    biometric_desc: 'Liez votre identité en toute sécurité à l\'aide d\'identifiants décentralisés (DID) et d\'une vérification biométrique.',
    platform_discovery: 'Découverte de la plateforme',
    platform_discovery_desc: 'Interagissez avec des clones IA de candidats pour comprendre leurs nuances sans le biais des médias traditionnels.',
    secure_balloting: 'Scrutin sécurisé',
    secure_balloting_desc: 'Exprimez votre vote dans un environnement E2EE accessible depuis n\'importe quel appareil vérifié dans le monde.',
    vault_verification: 'Vérification du coffre',
    vault_verification_desc: 'Recevez votre reçu cryptographique dans votre coffre d\'électeur, verrouillé par votre clé unique.',
    ready_to_lead: 'Prêt à montrer la voie ?',
    join_millions: 'Rejoignez 14 millions de citoyens mondiaux vérifiés participant à la prochaine évolution de la gouvernance.',
    create_identity: 'Créez votre identité d\'électeur',
    vision_matrix: 'Matrice de vision interactive',
    vision_matrix_desc: 'MAPPER LES CROYANCES FONDAMENTALES AUX RÉSULTATS DES DONNÉES RÉELLES',
    login_failed: 'Échec de la connexion. Veuillez vérifier vos identifiants et réessayer.',
    help_support: 'Aide & Support'
  },
  de: {
    settings: 'Einstellungen',
    profile: 'Profil',
    theme: 'Thema',
    language: 'Sprache',
    light: 'Hell',
    dark: 'Dunkel',
    save: 'Änderungen speichern',
    logout: 'Abmelden',
    dashboard: 'Dashboard',
    edit_profile: 'Profil bearbeiten',
    full_name: 'Vollständiger Name',
    email: 'E-Mail-Adresse',
    bio: 'Bio',
    avatar_url: 'Avatar-URL',
    appearance: 'Aussehen',
    preferences: 'Präferenzen',
    vault: 'Der Tresor',
    citizen: 'Bürger',
    verification_status: 'Verifizierungsstatus',
    live_ballots: 'Live-Abstimmungen',
    history: 'Beziehungshistorie',
    stats: 'Netzwerkstatistik',
    directives: 'Richtlinien',
    start_verification: 'Verifizierung starten',
    role: 'Rolle',
    voter: 'Wähler',
    candidate: 'Kandidat',
    switch_role: 'Rolle wechseln',
    hero_title: 'Demokratie, verfeinert.',
    hero_subtitle: 'Die weltweit fortschrittlichste Abstimmungsplattform. Sichere Identitätsprüfung, KI-Analyse in Echtzeit und absolute kryptografische Transparenz.',
    begin_journey: 'Beginnen Sie Ihre Reise',
    view_protocol: 'Protokoll ansehen',
    zero_knowledge: 'Null Wissen',
    zero_knowledge_desc: 'Ihre Identität wird verifiziert, aber Ihre Stimme bleibt mathematisch privat und unveränderlich.',
    ai_clarity: 'KI-Klarheit',
    ai_clarity_desc: 'Sofortiger Quervergleich der Kandidatenplattformen mit historischen Abstimmungsdaten über VoteEase AI.',
    total_audit: 'Gesamtaudit',
    total_audit_desc: 'Überprüfen Sie Ihren individualisierten Prüfpfad, um sicherzustellen, dass Ihre Stimme genau wie beabsichtigt gezählt wurde.',
    journey_title: 'Die VoteEase-Reise',
    journey_subtitle: 'Vier Schritte in eine transparentere Zukunft.',
    biometric_onboarding: 'Biometrisches Onboarding',
    biometric_desc: 'Verknüpfen Sie Ihre Identität sicher mit dezentralen Identifikatoren (DIDs) und biometrischer Verifizierung.',
    platform_discovery: 'Plattform-Entdeckung',
    platform_discovery_desc: 'Interagieren Sie mit KI-Klonen von Kandidaten, um deren Nuancen ohne traditionelle Medienberichterstattung zu verstehen.',
    secure_balloting: 'Sichere Stimmabgabe',
    secure_balloting_desc: 'Geben Sie Ihre Stimme in einer E2EE-Umgebung ab, die weltweit von jedem verifizierten Gerät aus zugänglich ist.',
    vault_verification: 'Tresor-Verifizierung',
    vault_verification_desc: 'Erhalten Sie Ihren kryptografischen Beleg in Ihrem Voter Vault, gesperrt mit Ihrem individuellen Schlüssel.',
    ready_to_lead: 'Bereit, den Weg zu weisen?',
    join_millions: 'Schließen Sie sich 14 Millionen verifizierten Bürgern weltweit an, die an der nächsten Evolution der Governance teilnehmen.',
    create_identity: 'Erstellen Sie Ihre Wähleridentität',
    vision_matrix: 'Interaktive Visionsmatrix',
    vision_matrix_desc: 'KERNÜBERZEUGUNGEN AUF DATENERGEBNISSE DER REALEN WELT ABBILDEN',
    login_failed: 'Anmeldung fehlgeschlagen. Bitte überprüfen Sie Ihre Zugangsdaten und versuchen Sie es erneut.',
    help_support: 'Hilfe & Support'
  },
  hi: {
    settings: 'सेटिंग्स',
    profile: 'प्रोफ़ाइल',
    theme: 'थीम',
    language: 'भाषा',
    light: 'लाइट',
    dark: 'डार्क',
    save: 'परिवर्तन सहेजें',
    logout: 'लॉगआउट',
    dashboard: 'डैशबोर्ड',
    edit_profile: 'प्रोफ़ाइल संपादित करें',
    full_name: 'पूरा नाम',
    email: 'ईमेल पता',
    bio: 'बायो',
    avatar_url: 'अवतार यूआरएल',
    appearance: 'रूप',
    preferences: 'वरीयताएँ',
    vault: 'तिजोरी',
    citizen: 'नागरिक',
    verification_status: 'सत्यापन स्थिति',
    live_ballots: 'लाइव मतपत्र',
    history: 'संबंधात्मक इतिहास',
    stats: 'नेटवर्क आँकड़े',
    directives: 'निर्देश',
    start_verification: 'सत्यापन शुरू करें',
    role: 'भूमिका',
    voter: 'मतदाता',
    candidate: 'उम्मीदवार',
    switch_role: 'भूमिका बदलें',
    hero_title: 'लोकतंत्र, परिष्कृत।',
    hero_subtitle: 'दुनिया का सबसे उन्नत वोटिंग प्लेटफॉर्म। सुरक्षित पहचान सत्यापन, रीयल-टाइम एआई विश्लेषण और पूर्ण क्रिप्टोग्राफिक पारदर्शिता।',
    begin_journey: 'अपनी यात्रा शुरू करें',
    view_protocol: 'प्रोटोकॉल देखें',
    zero_knowledge: 'शून्य ज्ञान',
    zero_knowledge_desc: 'आपकी पहचान सत्यापित है लेकिन आपका वोट गणितीय रूप से निजी और अपरिवर्तनीय रहता है।',
    ai_clarity: 'एआई स्पष्टता',
    ai_clarity_desc: 'VoteEase AI के माध्यम से ऐतिहासिक वोटिंग डेटा बनाम उम्मीदवार प्लेटफॉर्म का त्वरित क्रॉस-रेफरेंसिंग।',
    total_audit: 'कुल ऑडिट',
    total_audit_desc: 'यह सुनिश्चित करने के लिए कि आपकी आवाज ठीक उसी तरह से गिनी गई जैसा इरादा था, अपने व्यक्तिगत ऑडिट ट्रेल को सत्यापित करें।',
    journey_title: 'VoteEase यात्रा',
    journey_subtitle: 'एक अधिक पारदर्शी भविष्य की ओर चार कदम।',
    biometric_onboarding: 'बायोमेट्रिक ऑनबोर्डिंग',
    biometric_desc: 'विकेंद्रीकृत पहचानकर्ताओं (DIDs) और बायोमेट्रिक सत्यापन का उपयोग करके सुरक्षित रूप से अपनी पहचान लिंक करें।',
    platform_discovery: 'प्लेटफॉर्म खोज',
    platform_discovery_desc: 'पारंपरिक मीडिया पूर्वाग्रह के बिना उनकी बारीकियों को समझने के लिए उम्मीदवार एआई क्लोन के साथ बातचीत करें।',
    secure_balloting: 'सुरक्षित मतदान',
    secure_balloting_desc: 'विश्व स्तर पर किसी भी सत्यापित डिवाइस से सुलभ E2EE वातावरण के भीतर अपना वोट डालें।',
    vault_verification: 'तिजोरी सत्यापन',
    vault_verification_desc: 'अपने वोटर वॉल्ट में अपनी क्रिप्टोग्राफिक रसीद प्राप्त करें, जो आपकी अनूठी कुंजी के साथ लॉक है।',
    ready_to_lead: 'रास्ता दिखाने के लिए तैयार हैं?',
    join_millions: 'शासन के अगले विकास में भाग लेने वाले 1.4 करोड़ सत्यापित वैश्विक नागरिकों में शामिल हों।',
    create_identity: 'अपनी मतदाता पहचान बनाएं',
    vision_matrix: 'इंटरएक्टिव विजन मैट्रिक्स',
    vision_matrix_desc: 'कोर मान्यताओं को वास्तविक दुनिया के डेटा परिणामों से मैप करें',
    login_failed: 'लॉगिन विफल रहा। कृपया अपनी साख जांचें और पुन: प्रयास करें।',
    help_support: 'सहायता और समर्थन'
  },
  ur: {
    settings: 'ترتیبات',
    profile: 'پروفائل',
    theme: 'تھیم',
    language: 'زبان',
    light: 'روشن',
    dark: 'تاریک',
    save: 'تبدیلیاں محفوظ کریں',
    logout: 'لاگ آؤٹ',
    dashboard: 'ڈیش بورڈ',
    edit_profile: 'پروفائل میں ترمیم کریں',
    full_name: 'مکمل نام',
    email: 'ای میل پتہ',
    bio: 'بایو',
    avatar_url: 'اوتار یو آر ایل',
    appearance: 'ظاہری شکل',
    preferences: 'ترجیحات',
    vault: 'توجوری',
    citizen: 'شہری',
    verification_status: 'تصدیق کی حالت',
    live_ballots: 'لائیو بیلٹ',
    history: 'تاریخ',
    stats: 'نیٹ ورک کے اعدادوشمار',
    directives: 'ہدایات',
    start_verification: 'تصدیق شروع کریں',
    role: 'کردار',
    voter: 'ووٹر',
    candidate: 'امیدوار',
    switch_role: 'کردار تبدیل کریں',
    hero_title: 'جمہوریت، بہتر انداز میں۔',
    hero_subtitle: 'دنیا کا جدید ترین ووٹنگ پلیٹ فارم۔ محفوظ شناخت کی تصدیق، ریئل ٹائم AI تجزیہ، اور مکمل کرپٹو گرافک شفافیت۔',
    begin_journey: 'اپنے سفر کا آغاز کریں',
    view_protocol: 'پروٹوکول دیکھیں',
    zero_knowledge: 'زیرو نالج',
    zero_knowledge_desc: 'آپ کی شناخت کی تصدیق کی جاتی ہے لیکن آپ کا ووٹ ریاضیاتی طور پر نجی اور ناقابل تبدیل رہتا ہے۔',
    ai_clarity: 'AI وضاحت',
    ai_clarity_desc: 'VoteEase AI کے ذریعے تاریخی ووٹنگ ڈیٹا بمقابلہ امیدوار پلیٹ فارمز کا فوری حوالہ۔',
    total_audit: 'مکمل آڈٹ',
    total_audit_desc: 'یہ یقینی بنانے کے لیے کہ آپ کی آواز بالکل اسی طرح شمار کی گئی ہے جیسا کہ ارادہ تھا، اپنے انفرادی آڈٹ ٹریل کی تصدیق کریں۔',
    journey_title: 'VoteEase سفر',
    journey_subtitle: 'ایک زیادہ شفاف مستقبل کی طرف چار قدم۔',
    biometric_onboarding: 'بایومیٹرک آن بورڈنگ',
    biometric_desc: 'ڈی سینٹرلائزڈ آئیڈینٹی فائیرز (DIDs) اور بایومیٹرک تصدیق کا استعمال کرتے ہوئے اپنی شناخت کو محفوظ طریقے سے منسلک کریں۔',
    platform_discovery: 'پلیٹ فارم کی دریافت',
    platform_discovery_desc: 'روایتی میڈیا کے تعصب کے بغیر ان کی باریکیوں کو سمجھنے کے لیے امیدوار کے AI کلونز کے ساتھ بات چیت کریں۔',
    secure_balloting: 'محفوظ بیلٹنگ',
    secure_balloting_desc: 'عالمی سطح پر کسی بھی تصدیق شدہ ڈیوائس سے قابل رسائی E2EE ماحول کے اندر اپنا ووٹ ڈالیں۔',
    vault_verification: 'والٹ کی تصدیق',
    vault_verification_desc: 'اپنے ووٹر والٹ میں اپنی کرپٹو گرافک رسید حاصل کریں، جو آپ کی منفرد کلید کے ساتھ مقفل ہے۔',
    ready_to_lead: 'کیا آپ قیادت کے لیے تیار ہیں؟',
    join_millions: 'گورننس کے اگلے ارتقاء میں حصہ لینے والے 14 ملین تصدیق شدہ عالمی شہریوں میں شامل ہوں۔',
    create_identity: 'اپنی ووٹر شناخت بنائیں',
    vision_matrix: 'انٹرایکٹو ویژن میٹرکس',
    vision_matrix_desc: 'بنیادی عقائد کو حقیقی دنیا کے ڈیٹا کے نتائج سے جوڑیں',
    login_voter: 'ووٹر گیٹ وے',
    login_candidate: 'امیدوار پورٹل',
    auth_vector: 'اپنا محفوظ تصدیقی طریقہ منتخب کریں۔',
    voter_id: 'ووٹر آئی ڈی',
    mobile_phone: 'موبائل فون',
    global_account: 'عالمی اکاؤنٹ',
    candidate_hash: 'امیدوار ہیش آئی ڈی',
    official_credentials: 'سرکاری اسناد',
    corporate_email: 'کارپوریٹ ای میل استعمال کریں',
    identity_number: 'شناختی نمبر',
    request_validation: 'تصدیق کی درخواست کریں',
    switch_method: 'طریقہ تبدیل کریں',
    security_notice: 'سیکورٹی نوٹس: یہ پورٹل اینڈ ٹو اینڈ انکرپشن استعمال کرتا ہے۔ مرکزی نوڈس پر کوئی کچی اسناد محفوظ نہیں کی جاتی ہیں۔',
    login_failed: 'لاگ ان ناکام ہو گیا۔ براہ کرم اپنی اسناد چیک کریں اور دوبارہ کوشش کریں۔',
    help_support: 'مدد اور تعاون'
  }
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem('theme') as Theme) || 'light');
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('language') as Language) || 'en');
  const [direction, setDirection] = useState<'ltr' | 'rtl'>('ltr');

  useEffect(() => {
    localStorage.setItem('theme', theme);
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('language', language);
    const newDir = language === 'ur' ? 'rtl' : 'ltr';
    setDirection(newDir);
    document.documentElement.dir = newDir;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <SettingsContext.Provider value={{ theme, language, direction, setTheme, setLanguage, t }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context) throw new Error('useSettings must be used within SettingsProvider');
  return context;
};
